name: Clojure CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: cd datops-compute/ && lein deps && cd ../syncretism/ && lein deps
    - name: Run tests
      run: cd datops-compute/ && lein test && cd ../syncretism/ && lein test
